[theme]
primaryColor = "#0f380f"
backgroundColor = "#9bbc0f"
secondaryBackgroundColor = "#306230"
textColor = "#0f380f"
font = "monospace"

[server]
headless = true

[client]
showErrorDetails = false

[global]
# App metadata
appName = "ParkRun Time Predictor"
appDescription = "AI-powered ParkRun finish time prediction with Game Boy design"
appIcon = "🏃‍♂️"
appUrl = "https://www.parkrun.pl/krakow/"